- hosts: localhost
  gather_facts: False
  vars:
      instance_type: t2.micro
      security_group: buildsrv2 
      image: ami-08bac620dc84221e 
      region: eu-west-1 
      keypair: ansible
      count: 1

  tasks:

    - name: Create a security group
      ec2_group: 
        name: "{{ security_group }}"
        description: Security Group for prod pods
        region: "{{ region }}"
        rules:
          - proto: tcp
            type: ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            type: all
            cidr_ip: 0.0.0.0/0

#####     - name: Launch the new EC2 Instance
#####       local_action: ec2 
#####                      group={{ security_group }} 
  ##########                    instance_type={{ instance_type}} 
#####                    image={{ image }} 
   #####                   wait=true 
   #####                   region={{ region }} 
   ##### #####                  keypair={{ keypair }}
 #####                     count={{count}}
  #####       register: ec2